// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGfC3Z56hJmE5ZSxeMXsIlh3O_p1_Rir4',
    appId: '1:357378980414:web:223060400dd71836bcaf6f',
    messagingSenderId: '357378980414',
    projectId: 'twelve-stars-prod',
    authDomain: 'twelve-stars-prod.firebaseapp.com',
    storageBucket: 'twelve-stars-prod.firebasestorage.app',
    measurementId: 'G-KFP85H8XHF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLTABcDPa3g9PNnwiE6YuBk-VaFZH0qR0',
    appId: '1:357378980414:android:6823d4ac6344d247bcaf6f',
    messagingSenderId: '357378980414',
    projectId: 'twelve-stars-prod',
    storageBucket: 'twelve-stars-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU8gFEfOsI_y0uscnAsPrv5bEpCgIB-i4',
    appId: '1:357378980414:ios:295480f1c0b070b2bcaf6f',
    messagingSenderId: '357378980414',
    projectId: 'twelve-stars-prod',
    storageBucket: 'twelve-stars-prod.firebasestorage.app',
    iosBundleId: 'com.mweastwood.twelveStars',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU8gFEfOsI_y0uscnAsPrv5bEpCgIB-i4',
    appId: '1:357378980414:ios:295480f1c0b070b2bcaf6f',
    messagingSenderId: '357378980414',
    projectId: 'twelve-stars-prod',
    storageBucket: 'twelve-stars-prod.firebasestorage.app',
    iosBundleId: 'com.mweastwood.twelveStars',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'PLACEHOLDER_API_KEY',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'twelve-stars-prod',
    authDomain: 'twelve-stars-prod.firebaseapp.com',
    storageBucket: 'twelve-stars-prod.firebasestorage.app',
  );
}
