// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeMwcCYGRUk6AX5GFMMafuRFxgkNcOTUg',
    appId: '1:330103529092:web:39858ba62ae839e67aacd1',
    messagingSenderId: '330103529092',
    projectId: 'twelve-stars-dev',
    authDomain: 'twelve-stars-dev.firebaseapp.com',
    storageBucket: 'twelve-stars-dev.firebasestorage.app',
    measurementId: 'G-NXJ4ESS484',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEH4MPEnj0at_hNG0nBMXTGR6UicXPExg',
    appId: '1:330103529092:android:1ad47657049194a17aacd1',
    messagingSenderId: '330103529092',
    projectId: 'twelve-stars-dev',
    storageBucket: 'twelve-stars-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArHS0Aa0mqKP55O_4rzFVs3sO6H9PNetE',
    appId: '1:330103529092:ios:b950fe7c7ca093bf7aacd1',
    messagingSenderId: '330103529092',
    projectId: 'twelve-stars-dev',
    storageBucket: 'twelve-stars-dev.firebasestorage.app',
    iosBundleId: 'com.mweastwood.twelveStars',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArHS0Aa0mqKP55O_4rzFVs3sO6H9PNetE',
    appId: '1:330103529092:ios:b950fe7c7ca093bf7aacd1',
    messagingSenderId: '330103529092',
    projectId: 'twelve-stars-dev',
    storageBucket: 'twelve-stars-dev.firebasestorage.app',
    iosBundleId: 'com.mweastwood.twelveStars',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'PLACEHOLDER_API_KEY',
    appId: '1:000000000000:web:0000000000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'twelve-stars-dev',
    authDomain: 'twelve-stars-dev.firebaseapp.com',
    storageBucket: 'twelve-stars-dev.firebasestorage.app',
  );
}
