class BibleBook {
  final int bookNumber;
  final String bookName;
  final String abbrev;
  final int chaptersCount;
  final String category;
  final String testament;

  const BibleBook({
    required this.bookNumber,
    required this.bookName,
    required this.abbrev,
    required this.chaptersCount,
    required this.category,
    required this.testament,
  });
}

const List<BibleBook> catholicBooks = [
  // Old Testament - Pentateuch
  BibleBook(
    bookNumber: 1,
    bookName: 'Genesis',
    abbrev: 'GEN',
    chaptersCount: 50,
    category: 'Pentateuch',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 2,
    bookName: 'Exodus',
    abbrev: 'EXO',
    chaptersCount: 40,
    category: 'Pentateuch',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 3,
    bookName: 'Leviticus',
    abbrev: 'LEV',
    chaptersCount: 27,
    category: 'Pentateuch',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 4,
    bookName: 'Numbers',
    abbrev: 'NUM',
    chaptersCount: 36,
    category: 'Pentateuch',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 5,
    bookName: 'Deuteronomy',
    abbrev: 'DEU',
    chaptersCount: 34,
    category: 'Pentateuch',
    testament: 'Old Testament',
  ),

  // Old Testament - Historical
  BibleBook(
    bookNumber: 6,
    bookName: 'Joshua',
    abbrev: 'JOS',
    chaptersCount: 24,
    category: 'Historical Books',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 7,
    bookName: 'Judges',
    abbrev: 'JDG',
    chaptersCount: 21,
    category: 'Historical Books',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 8,
    bookName: 'Ruth',
    abbrev: 'RUT',
    chaptersCount: 4,
    category: 'Historical Books',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 9,
    bookName: '1 Samuel',
    abbrev: '1SA',
    chaptersCount: 31,
    category: 'Historical Books',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 10,
    bookName: '2 Samuel',
    abbrev: '2SA',
    chaptersCount: 24,
    category: 'Historical Books',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 11,
    bookName: '1 Kings',
    abbrev: '1KI',
    chaptersCount: 22,
    category: 'Historical Books',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 12,
    bookName: '2 Kings',
    abbrev: '2KI',
    chaptersCount: 25,
    category: 'Historical Books',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 13,
    bookName: '1 Chronicles',
    abbrev: '1CH',
    chaptersCount: 29,
    category: 'Historical Books',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 14,
    bookName: '2 Chronicles',
    abbrev: '2CH',
    chaptersCount: 36,
    category: 'Historical Books',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 15,
    bookName: 'Ezra',
    abbrev: 'EZR',
    chaptersCount: 10,
    category: 'Historical Books',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 16,
    bookName: 'Nehemiah',
    abbrev: 'NEH',
    chaptersCount: 13,
    category: 'Historical Books',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 17,
    bookName: 'Tobit',
    abbrev: 'TOB',
    chaptersCount: 14,
    category: 'Historical Books',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 18,
    bookName: 'Judith',
    abbrev: 'JDT',
    chaptersCount: 16,
    category: 'Historical Books',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 19,
    bookName: 'Esther',
    abbrev: 'EST',
    chaptersCount: 10,
    category: 'Historical Books',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 45,
    bookName: '1 Maccabees',
    abbrev: '1MA',
    chaptersCount: 16,
    category: 'Historical Books',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 46,
    bookName: '2 Maccabees',
    abbrev: '2MA',
    chaptersCount: 15,
    category: 'Historical Books',
    testament: 'Old Testament',
  ),

  // Old Testament - Wisdom
  BibleBook(
    bookNumber: 20,
    bookName: 'Job',
    abbrev: 'JOB',
    chaptersCount: 42,
    category: 'Wisdom Books',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 21,
    bookName: 'Psalms',
    abbrev: 'PSA',
    chaptersCount: 150,
    category: 'Wisdom Books',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 22,
    bookName: 'Proverbs',
    abbrev: 'PRO',
    chaptersCount: 31,
    category: 'Wisdom Books',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 23,
    bookName: 'Ecclesiastes',
    abbrev: 'ECC',
    chaptersCount: 12,
    category: 'Wisdom Books',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 24,
    bookName: 'Canticle of Canticles',
    abbrev: 'SNG',
    chaptersCount: 8,
    category: 'Wisdom Books',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 25,
    bookName: 'Wisdom',
    abbrev: 'WIS',
    chaptersCount: 19,
    category: 'Wisdom Books',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 26,
    bookName: 'Sirach',
    abbrev: 'SIR',
    chaptersCount: 51,
    category: 'Wisdom Books',
    testament: 'Old Testament',
  ),

  // Old Testament - Prophets
  BibleBook(
    bookNumber: 27,
    bookName: 'Isaiah',
    abbrev: 'ISA',
    chaptersCount: 66,
    category: 'Prophets',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 28,
    bookName: 'Jeremiah',
    abbrev: 'JER',
    chaptersCount: 52,
    category: 'Prophets',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 29,
    bookName: 'Lamentations',
    abbrev: 'LAM',
    chaptersCount: 5,
    category: 'Prophets',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 30,
    bookName: 'Baruch',
    abbrev: 'BAR',
    chaptersCount: 6,
    category: 'Prophets',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 31,
    bookName: 'Ezekiel',
    abbrev: 'EZK',
    chaptersCount: 48,
    category: 'Prophets',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 32,
    bookName: 'Daniel',
    abbrev: 'DAN',
    chaptersCount: 14,
    category: 'Prophets',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 33,
    bookName: 'Hosea',
    abbrev: 'HOS',
    chaptersCount: 14,
    category: 'Prophets',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 34,
    bookName: 'Joel',
    abbrev: 'JOL',
    chaptersCount: 3,
    category: 'Prophets',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 35,
    bookName: 'Amos',
    abbrev: 'AMO',
    chaptersCount: 9,
    category: 'Prophets',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 36,
    bookName: 'Obadiah',
    abbrev: 'OBA',
    chaptersCount: 1,
    category: 'Prophets',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 37,
    bookName: 'Jonah',
    abbrev: 'JON',
    chaptersCount: 4,
    category: 'Prophets',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 38,
    bookName: 'Micah',
    abbrev: 'MIC',
    chaptersCount: 7,
    category: 'Prophets',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 39,
    bookName: 'Nahum',
    abbrev: 'NAM',
    chaptersCount: 3,
    category: 'Prophets',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 40,
    bookName: 'Habakkuk',
    abbrev: 'HAB',
    chaptersCount: 3,
    category: 'Prophets',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 41,
    bookName: 'Zephaniah',
    abbrev: 'ZEP',
    chaptersCount: 3,
    category: 'Prophets',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 42,
    bookName: 'Haggai',
    abbrev: 'HAG',
    chaptersCount: 2,
    category: 'Prophets',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 43,
    bookName: 'Zechariah',
    abbrev: 'ZEC',
    chaptersCount: 14,
    category: 'Prophets',
    testament: 'Old Testament',
  ),
  BibleBook(
    bookNumber: 44,
    bookName: 'Malachi',
    abbrev: 'MAL',
    chaptersCount: 4,
    category: 'Prophets',
    testament: 'Old Testament',
  ),

  // New Testament - Gospels & Acts
  BibleBook(
    bookNumber: 49,
    bookName: 'Matthew',
    abbrev: 'MAT',
    chaptersCount: 28,
    category: 'Gospels & Acts',
    testament: 'New Testament',
  ),
  BibleBook(
    bookNumber: 50,
    bookName: 'Mark',
    abbrev: 'MRK',
    chaptersCount: 16,
    category: 'Gospels & Acts',
    testament: 'New Testament',
  ),
  BibleBook(
    bookNumber: 51,
    bookName: 'Luke',
    abbrev: 'LUK',
    chaptersCount: 24,
    category: 'Gospels & Acts',
    testament: 'New Testament',
  ),
  BibleBook(
    bookNumber: 52,
    bookName: 'John',
    abbrev: 'JHN',
    chaptersCount: 21,
    category: 'Gospels & Acts',
    testament: 'New Testament',
  ),
  BibleBook(
    bookNumber: 53,
    bookName: 'Acts',
    abbrev: 'ACT',
    chaptersCount: 28,
    category: 'Gospels & Acts',
    testament: 'New Testament',
  ),

  // New Testament - Epistles
  BibleBook(
    bookNumber: 54,
    bookName: 'Romans',
    abbrev: 'ROM',
    chaptersCount: 16,
    category: 'Epistles',
    testament: 'New Testament',
  ),
  BibleBook(
    bookNumber: 55,
    bookName: '1 Corinthians',
    abbrev: '1CO',
    chaptersCount: 16,
    category: 'Epistles',
    testament: 'New Testament',
  ),
  BibleBook(
    bookNumber: 56,
    bookName: '2 Corinthians',
    abbrev: '2CO',
    chaptersCount: 13,
    category: 'Epistles',
    testament: 'New Testament',
  ),
  BibleBook(
    bookNumber: 57,
    bookName: 'Galatians',
    abbrev: 'GAL',
    chaptersCount: 6,
    category: 'Epistles',
    testament: 'New Testament',
  ),
  BibleBook(
    bookNumber: 58,
    bookName: 'Ephesians',
    abbrev: 'EPH',
    chaptersCount: 6,
    category: 'Epistles',
    testament: 'New Testament',
  ),
  BibleBook(
    bookNumber: 59,
    bookName: 'Philippians',
    abbrev: 'PHP',
    chaptersCount: 4,
    category: 'Epistles',
    testament: 'New Testament',
  ),
  BibleBook(
    bookNumber: 60,
    bookName: 'Colossians',
    abbrev: 'COL',
    chaptersCount: 4,
    category: 'Epistles',
    testament: 'New Testament',
  ),
  BibleBook(
    bookNumber: 61,
    bookName: '1 Thessalonians',
    abbrev: '1TH',
    chaptersCount: 5,
    category: 'Epistles',
    testament: 'New Testament',
  ),
  BibleBook(
    bookNumber: 62,
    bookName: '2 Thessalonians',
    abbrev: '2TH',
    chaptersCount: 3,
    category: 'Epistles',
    testament: 'New Testament',
  ),
  BibleBook(
    bookNumber: 64,
    bookName: '1 Timothy',
    abbrev: '1TI',
    chaptersCount: 6,
    category: 'Epistles',
    testament: 'New Testament',
  ),
  BibleBook(
    bookNumber: 65,
    bookName: '2 Timothy',
    abbrev: '2TI',
    chaptersCount: 4,
    category: 'Epistles',
    testament: 'New Testament',
  ),
  BibleBook(
    bookNumber: 66,
    bookName: 'Titus',
    abbrev: 'TIT',
    chaptersCount: 3,
    category: 'Epistles',
    testament: 'New Testament',
  ),
  BibleBook(
    bookNumber: 67,
    bookName: 'Philemon',
    abbrev: 'PHM',
    chaptersCount: 1,
    category: 'Epistles',
    testament: 'New Testament',
  ),
  BibleBook(
    bookNumber: 68,
    bookName: 'Hebrews',
    abbrev: 'HEB',
    chaptersCount: 13,
    category: 'Epistles',
    testament: 'New Testament',
  ),
  BibleBook(
    bookNumber: 69,
    bookName: 'James',
    abbrev: 'JAM',
    chaptersCount: 5,
    category: 'Epistles',
    testament: 'New Testament',
  ),
  BibleBook(
    bookNumber: 70,
    bookName: '1 Peter',
    abbrev: '1PE',
    chaptersCount: 5,
    category: 'Epistles',
    testament: 'New Testament',
  ),
  BibleBook(
    bookNumber: 71,
    bookName: '2 Peter',
    abbrev: '2PE',
    chaptersCount: 3,
    category: 'Epistles',
    testament: 'New Testament',
  ),
  BibleBook(
    bookNumber: 72,
    bookName: '1 John',
    abbrev: '1JN',
    chaptersCount: 5,
    category: 'Epistles',
    testament: 'New Testament',
  ),
  BibleBook(
    bookNumber: 73,
    bookName: '2 John',
    abbrev: '2JN',
    chaptersCount: 1,
    category: 'Epistles',
    testament: 'New Testament',
  ),
  BibleBook(
    bookNumber: 74,
    bookName: '3 John',
    abbrev: '3JN',
    chaptersCount: 1,
    category: 'Epistles',
    testament: 'New Testament',
  ),
  BibleBook(
    bookNumber: 75,
    bookName: 'Jude',
    abbrev: 'JUD',
    chaptersCount: 1,
    category: 'Epistles',
    testament: 'New Testament',
  ),

  // New Testament - Prophecy
  BibleBook(
    bookNumber: 76,
    bookName: 'Revelation',
    abbrev: 'REV',
    chaptersCount: 22,
    category: 'Prophecy',
    testament: 'New Testament',
  ),
];
