name: Deploy (Dev)

on:
  workflow_run:
    workflows: ["Test Suite"]
    branches: [main]
    types: 
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy_dev_firebase_web:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    defaults:
      run:
        working-directory: ./app

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web App
        run: flutter build web --release --target lib/main_dev.dart

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: ./app
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TWELVE_STARS_DEV }}'
          channelId: live
          projectId: twelve-stars-dev
          firebaseToolsVersion: '15.22.2'
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

  deploy_dev_firebase_android:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    
    defaults:
      run:
        working-directory: ./app

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Decode Android Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/release.keystore

      - name: Build Android APK
        run: flutter build apk --release --flavor dev --target lib/main_dev.dart
        env:
          ANDROID_KEYSTORE_PATH: "release.keystore"
          ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
          ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: "1:330103529092:android:1ad47657049194a17aacd1"
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TWELVE_STARS_DEV }}
          groups: testers
          file: app/build/app/outputs/flutter-apk/app-dev-release.apk
